namespace StreamDeck.Generators.Tests
{
    using StreamDeck.Generators.Tests.Helpers;

    /// <summary>
    /// Provides assertions for <see cref="UuidPropertySourceGenerator"/>.
    /// </summary>
    [TestFixture]
    public class UuidPropertySourceGeneratorTests
    {
        /// <summary>
        /// The hint hame prefix.
        /// </summary>
        private const string HINT_PREFIX = "StreamDeck.Generators\\StreamDeck.Generators.UuidPropertySourceGenerator\\";

        /// <summary>
        /// Asserts no additional syntax trees are added when there are no actions.
        /// </summary>
        [TestCase(TestName = "No actions")]
        public void NoActions()
        {
            // Arrange, act.
            var (compilation, _) = SourceGeneratorTests.Run(new UuidPropertySourceGenerator(), sourceText: string.Empty);

            // Assert.
            SourceGeneratorTests.VerifySyntaxTrees(compilation);
        }

        /// <summary>
        /// Asserts that non-partial classes are ignored.
        /// </summary>
        [TestCase(TestName = "Non partial classes")]
        public void NonPartialClasses()
        {
            // Arrange.
            const string sourceText = """
                [StreamDeck.Action(UUID = "com.tests.example.myaction")]
                public class MyAction {}
                """;

            // Act.
            var (compilation, _) = SourceGeneratorTests.Run(new UuidPropertySourceGenerator(), sourceText);

            // Assert.
            SourceGeneratorTests.VerifySyntaxTrees(compilation);
        }

        /// <summary>
        /// Asserts that a class with a property of "UUID" is ignored.
        /// </summary>
        [TestCase(TestName = "Property name already exists")]
        public void PropertyExists()
        {
            const string sourceText = """
                [StreamDeck.Action(UUID = "com.tests.example.myaction")]
                public partial class MyAction
                {
                    public const string UUID = "foo";
                }
                """;

            // Act.
            var (compilation, _) = SourceGeneratorTests.Run(new UuidPropertySourceGenerator(), sourceText);

            // Assert.
            SourceGeneratorTests.VerifySyntaxTrees(compilation);
        }

            /// <summary>
            /// Asserts that a class with a method of "UUID" is ignored.
            /// </summary>
            [TestCase(TestName = "Method name already exists")]
        public void MethodExists()
        {
            // Arrange.
            const string sourceText = """
                [StreamDeck.Action(UUID = "com.tests.example.myaction")]
                public partial class MyAction
                {
                    public void UUID()
                    {
                    }
                }
                """;

            // Act.
            var (compilation, _) = SourceGeneratorTests.Run(new UuidPropertySourceGenerator(), sourceText);

            // Assert.
            SourceGeneratorTests.VerifySyntaxTrees(compilation);
        }

        /// <summary>
        /// Asserts the UUID property is written when the class is on the global namespace.
        /// </summary>
        [TestCase(TestName = "Single action on the global namespace")]
        public void GlobalScopeAction()
        {
            // Arrange.
            const string sourceText = """
                [StreamDeck.Action(UUID = "com.tests.example.myaction")]
                public partial class MyAction {}
                """;

            // Act.
            var (compilation, _) = SourceGeneratorTests.Run(new UuidPropertySourceGenerator(), sourceText);

            // Assert.
            SourceGeneratorTests.VerifySyntaxTrees(
                compilation,
                (
                    HintName: $"{HINT_PREFIX}MyAction.0.g.cs",
                    SourceText: """
                    // <auto-generated />

                    partial class MyAction
                    {
                        /// <summary>
                        /// Gets the unique identifier of the action as defined by the <see cref="StreamDeck.ActionAttribute.UUID"/>.
                        /// </summary>
                        public const string UUID = "com.tests.example.myaction";
                    }

                    """
                ));
        }

        /// <summary>
        /// Asserts the UUID property is written when the class is on a custom namespace.
        /// </summary>
        [TestCase(TestName = "Single action on a defined namespace")]
        public void NamespaceScopeAction()
        {
            // Arrange.
            const string sourceText = """
                namespace Foo.Bar
                {
                    [StreamDeck.Action(UUID = "com.tests.example.myaction")]
                    public partial class MyAction {}
                }
                """;

            // Act.
            var (compilation, _) = SourceGeneratorTests.Run(new UuidPropertySourceGenerator(), sourceText);

            // Assert.
            SourceGeneratorTests.VerifySyntaxTrees(
                compilation,
                (
                    HintName: $"{HINT_PREFIX}MyAction.0.g.cs",
                    SourceText: """
                    // <auto-generated />

                    namespace Foo.Bar
                    {
                        partial class MyAction
                        {
                            /// <summary>
                            /// Gets the unique identifier of the action as defined by the <see cref="StreamDeck.ActionAttribute.UUID"/>.
                            /// </summary>
                            public const string UUID = "com.tests.example.myaction";
                        }
                    }

                    """
                ));
        }

        /// <summary>
        /// Asserts the UUID property is written when the multiple classes are defined, on the global namespace and a custom namespace.
        /// </summary>
        [TestCase(TestName = "Two actions, one on either namespace scope")]
        public void GlobalScopeAndNamespaceScopeAction()
        {
            // Arrange.
            const string sourceText = """
                [StreamDeck.Action(UUID = "com.tests.example.myaction")]
                public partial class MyAction {}

                namespace Foo.Bar
                {
                    [StreamDeck.Action(UUID = "com.tests.example.myotheraction")]
                    public partial class MyOtherAction {}
                }
                """;

            // Act.
            var (compilation, _) = SourceGeneratorTests.Run(new UuidPropertySourceGenerator(), sourceText);

            // Assert.
            SourceGeneratorTests.VerifySyntaxTrees(
                compilation,
                (
                    HintName: $"{HINT_PREFIX}MyAction.0.g.cs",
                    SourceText: """
                    // <auto-generated />

                    partial class MyAction
                    {
                        /// <summary>
                        /// Gets the unique identifier of the action as defined by the <see cref="StreamDeck.ActionAttribute.UUID"/>.
                        /// </summary>
                        public const string UUID = "com.tests.example.myaction";
                    }

                    """
                ),
                (
                    HintName: $"{HINT_PREFIX}MyOtherAction.0.g.cs",
                    SourceText: """
                    // <auto-generated />

                    namespace Foo.Bar
                    {
                        partial class MyOtherAction
                        {
                            /// <summary>
                            /// Gets the unique identifier of the action as defined by the <see cref="StreamDeck.ActionAttribute.UUID"/>.
                            /// </summary>
                            public const string UUID = "com.tests.example.myotheraction";
                        }
                    }

                    """
                ));
        }

        /// <summary>
        /// Asserts the UUID property is written when the classes have a UUID conflict.
        /// </summary>
        [TestCase(TestName = "Multiple actions with duplicate UUID")]
        public void MultipleActionsWithDuplicateUUID()
        {
            // Arrange.
            const string sourceText = """
                [StreamDeck.Action(UUID = "com.tests.example.myaction")]
                public partial class MyAction {}

                [StreamDeck.Action(UUID = "com.tests.example.myaction")]
                public partial class MyAction {}
                """;

            // Act.
            var (compilation, _) = SourceGeneratorTests.Run(new UuidPropertySourceGenerator(), sourceText);

            // Assert.
            SourceGeneratorTests.VerifySyntaxTrees(
                compilation,
                (
                    HintName: $"{HINT_PREFIX}MyAction.0.g.cs",
                    SourceText: """
                    // <auto-generated />

                    partial class MyAction
                    {
                        /// <summary>
                        /// Gets the unique identifier of the action as defined by the <see cref="StreamDeck.ActionAttribute.UUID"/>.
                        /// </summary>
                        public const string UUID = "com.tests.example.myaction";
                    }

                    """
                ),
                (
                    HintName: $"{HINT_PREFIX}MyAction.1.g.cs",
                    SourceText: """
                    // <auto-generated />

                    partial class MyAction
                    {
                        /// <summary>
                        /// Gets the unique identifier of the action as defined by the <see cref="StreamDeck.ActionAttribute.UUID"/>.
                        /// </summary>
                        public const string UUID = "com.tests.example.myaction";
                    }

                    """
                ));
        }
    }
}
