name: Main Workflow

on: [push]

jobs:
  main:
    runs-on: windows-latest
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build
      run: dotnet build ./src/SharpDeck/ --configuration Release
    - name: Test
      run: dotnet test ./src/SharpDeck.Tests/
